root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main.exe"
cmd = "go build -o tmp/main.exe ./cmd/server"
include = ["**/*.go"]
exclude = ["tmp/*", "client/*"]
ignore = ["tmp/*"]

[deploy]
cmd = "tmp/main.exe"
watch_dir = ["."]
watch_ext = ["go"]
